### ISSUE TITLE
Epic: Image Classifier

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-classifier#1]
Once we are uploading images dwyl/imgup#51 
We want to classify the images and suggest meta tags to describe the images so that they become "searchable".
That means pulling any text out of images using OCR.
And attempting to find any detail in images that can be useful.

We aren't going build our own models from scratch. but we are going to ...

# Todo

+ [x] Research the available models, services/APIs we can use to send an image that classify images
+ [x] Research available OCR services or models.
  + [x] If there is an _Open Source_ OCR model we can run on our own infra e.g. €20/month on Fly.io share!!
+ [x] Images that are uploaded from a Camera or Smart Phone contain `metadata` including `camera type`/`model`, `location` (where the photo was taken), `ISO`, `Shutter`, `Focal Length`, `Original Resolution`, etc. We want to capture this and feed it into the classifier. #3 
+ [x] The objective of the classifier is to _attempt_ to _describe_ the image and return a few keywords. 

+ [x] If it makes more sense to have this as a standalone `app` (_separate from `imgup`_) then feel free to create a `new` repo! Then just send the data to the standalone app and receive `JSON` data in response. 💭 

@LuchoTurtle please leave comments with your research. 🙏 

# Context

We want to be able to upload images in our `App` and have them become an `item` of content. 
i.e. I take a photo of a messy kitchen and it becomes "Tidy The Kitchen" with a small thumbnail of the image.
If I tap on the thumbnail I see the full-screen. But the _Text_ is the important part.

The reason we want to have a "**_Visual_ Todo List**" is that it becomes easy for people who don't yet read (think toddlers) or people who don't read well (people who only have basic literacy) to follow instructions.
