### ISSUE TITLE
Feat: Comparing Pre-trained Image Classification Models

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-classifier#12]
@LuchoTurtle as you've noted in the [`README.md > What about other models?`](https://github.com/dwyl/image-classifier/tree/d7205ca4a97a1d582436d5cc9d781eb80b6311b2#6-what-about-other-models) section:

<img width="854" alt="image" src="https://github.com/dwyl/image-classifier/assets/194400/86e0d251-2ccd-4e94-98f4-2f5b6c725932">

The bigger the model the more resources consumed and _slower_ the result ... 💰 ⏳ 
This is your opportunity to do some actual Software Engineering and write-up the findings!

# Todo

+ [x] Create a new file `model-comparison.md` 
+ [x] Give a brief intro to _why_ someone would want to use a smaller/bigger model (e.g. for a low-stakes demo)
+ [ ] Deploy all three models: 
  1. `ResNet-50` 
  2. `BLIP` (base)
  3. `BLIP` _large_. 
+ [x] Compare the response time and classification string for the _same_ input images. 
  + [x] Pick 7 sample images. e.g. a Pet, Vehicle, Food, Person, Landscape, Wild Animal,  Random (Your Choice). 
+ [x] Create a _Summary_ Table with the columns:
  + Model Name
  + Size in `GB`
  + `RAM` required to run it
  + Approximate monthly cost on Fly.io (other platforms may be cheaper/more expensive; we're just using Fly.io for illustration purposes...)
  + Machine Startup-time from "paused" (cold boot) (just to show the initial page)
  + Approximate response time for an image. (put the average in the summary table)
  + Sample classification string

+ [ ] Create a Detail Table with the columns:
  + Model Name
  + Image thumbnail
  + Image Description returned by the classifier/model
  + Response time in `ms`

Each row in the Detail table should be an entry for a given model.
Cluster the results together e.g. the Cat/Kitten pick for each model should be together to facilitate comparison.

> [!NOTE]
> Looks like https://huggingface.co/Salesforce/blip-image-captioning-base/tree/main was last updated `11 months ago` ... 
> <img width="1216" alt="blip-image-captioning-base-last-updated-11-months-ago" src="https://github.com/dwyl/image-classifier/assets/194400/87742e6c-fcf3-4554-9895-bde794960533">
> Can we try https://github.com/salesforce/LAVIS ? 💡

**Comment by nelsonic** [comment]
@LuchoTurtle you asked on Standup if we should compare "just" these 3 models.
I think a "small", "medium" and "large" is a good starting point.
But if we get feedback from people on HN (once you post the link 😉) that they want more models compared,
then more can easily be added.

**Comment by LuchoTurtle** [comment]
While it's true that there isn't a *de facto* leaderboard for image captioning (part of computer vision) tasks like [`MTEB`](https://huggingface.co/spaces/mteb/leaderboard), there's a reason for it.

From what I've seen, the most regarded benchmark comparison there that puts different models side to side is https://huggingface.co/spaces/mteb/leaderboard.

It doesn't, however, have **multimodal** models (models that can receive multiple types of input), which `BLIP` is. I can try to get a small benchmark going but I'm afraid I don't know how I can make it "data sciency" and compare accuracy between the models you've suggested because they're `one-shot models`. 

What I'm thinking is perhaps comparing the absolute value between embeddings of a dataset `ImageNet` image and what the model like `BLIP` yields to check for accuracy.

I'll see to it 👌

**Comment by nelsonic** [comment]
The only thing we want is a _real-world_ comparison. 
i.e. We wanted to use an _existing_ model to classify images.
We compared these 3 models along 3 dimensions: Quality, Speed & Cost. 
This is _way_ more interesting to a decision maker than the synthetic benchmark/leaderboard. 
The Massive Text Embedding Benchmark (MTEB) Leaderboard is _interesting_ for Embeddings ...
<img width="1420" alt="image" src="https://github.com/dwyl/image-classifier/assets/194400/1fc3084f-f44e-4406-bd48-82010fe7fb06">

But your _average_ person has _no clue_ what all the columns in the tables mean.
Is a bigger number _better_ or _worse_? in some cases the "best" model has a worse score than others.
How is the ranking calculated? 

Anyway, we just want to compare the models that are available to _us_ for the purposes of classifying images. 
The table will be useful to us and interesting to several thousand other people on HN. 👍

**Comment by ndrean** [comment]
Just again my few euro, but I already tried microsoft and facebook and found the results bad, when compared to Saleforce/Blip.

microsoft
![Screenshot 2023-11-15 at 12 32 42](https://github.com/dwyl/image-classifier/assets/6793008/7ed08675-fb59-4165-a5fa-75e5d0ff920e)

salesforce/blip-base
![Screenshot 2023-11-15 at 12 36 26](https://github.com/dwyl/image-classifier/assets/6793008/fd3ea05c-5f9e-44c7-8c06-4bbed5b5c6db)

**Comment by nelsonic** [comment]
Much more descriptive: 
<img width="1259" alt="image" src="https://github.com/dwyl/image-classifier/assets/194400/5f6d5cd8-261a-46a3-8213-0a1344c07f85">

But app still takes a _very_ long time to load ... ⏳

**Comment by LuchoTurtle** [comment]
@nelsonic do you mean to load or to get a description?
If it takes time to load, it's probably because the machine was "asleep" and you had to boot it again/"wake it" (because we've set machine instances to sleep after a period of inactivity to save costs). This is very much normal. I've inclusively just opened the link and it loaded instantly.

If there's a problem with the time to load the app from a machine that's asleep, that's another issue entirely. Even then, by caching the models, it takes seconds tops, instead of minutes that would have to wasted by re-downloading the models on every app startup.

**Comment by nelsonic** [comment]
Yeah, agree that Fly.io machine wake time is a separate issue that isn't really under our control. 
You've done a good job of caching the model. 👍 
We just need to trigger the "wake from sleep" when someone views the `README.md` as noted in: #11 

Meanwhile the descriptions are _much_ better! 

<img width="969" alt="image" src="https://github.com/dwyl/image-classifier/assets/194400/d6c5ac44-60bd-4fa2-a4bc-7e1998ed968f">

**Comment by ndrean** [comment]
I suppose you know you can set `min_machines_running = 1` in the "fly.toml", depends if you want this.

**Comment by nelsonic** [comment]
Yeah, when we “productionise” this feature, we will set it to be “always on” (min=1) but for now we just want to focus on cold startup time. 👌
