### ISSUE TITLE
Prepare the repo for `public` share on `HN` 🚀 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-classifier#22]
@LuchoTurtle you've done a _superb_ job of building a _fully functional_ image captioning app! 😍 🎉 
Now it's time to get some `credit` for it  💳 😉 by submitting a "**Show HN**" :shipit: 
And in the process **raise your `public` profile** for applying to `#NextAdventure` 🚀 

# Todo

+ [ ] Address the start-up time (currently `25sec`): https://github.com/dwyl/image-classifier/issues/20
  + [ ] And/or create an endpoint to serve a `1x1px GIF` to start the app _proactively_ when someone is reading the `README.md` ref: https://github.com/dwyl/ping/issues/7 

+ [ ] Improve the `Why?` section of `README.md` to answer the Reader's question succinctly. 

Currently it's: https://github.com/dwyl/image-classifier/tree/a3c8c3bf79a0f5e7bca160b6e460d883bc6e3973#why-
<img width="922" alt="image" src="https://github.com/dwyl/image-classifier/assets/194400/a45adadf-8582-4fa7-8476-6b38e153286c">

This is _good_ for an _internally-focussed_ tutorial for _us_ ... 👍 
but as an LLM-curious person casually reading on `HN`, 👀 
this isn't going to "hook" me into reading a `5k word` tutorial for `30+ mins` ... ⏳ 

```md
# Why? 💭 

We needed a fully-offline capable (no 3rd party APIs/Services) image captioning service 
using a state-of-the-art pre-trained image model to describe images uploaded in our 
[`App`](https://github.com/dwyl/app).

# What?

A step-by-step tutorial building a fully functional 
`Phoenix LiveView` web application that allows anyone 
to upload an image and have it described 
by the `Open Source` `BLIP` image captioning (`Large`) model.

```

+ [ ] Simplify layout of homepage of the App and add _examples_: https://github.com/dwyl/image-classifier/issues/7
+ [ ] _Prepare_ Intro/Demo `GIF`: https://github.com/dwyl/image-classifier/issues/21
+ [ ] Add demo `GIF` to intro of `README.md` 
  + [ ] `GIF` should be below the `badges` and _above_ the `TOC`: 

<img width="912" alt="intro-gif-position" src="https://github.com/dwyl/image-classifier/assets/194400/587caab9-c812-47fd-8ad6-70ea981a4581">

+ [ ] Study the 20 most successful "Show HN" posts: https://hn.algolia.com/?query=show+hn&sort=byPopularity (spend 1-2 mins skimming each one to extract the info - or use `ChatGPT` to do some pre-analysis if you think it will be useful ...)
Summarise what you learned as comments in this issue thread. 💬 🙏 

+ [ ] Carefully craft your `Show HN` Title to maximise its chance of success. 💭 
+ [ ] Submit your `Show HN`!! 🚀 
+ [ ] Share the link so we can up-vote it. 🔗 ⬆️ 
  + [ ] Get _everyone_ you know to up-vote it so it gets and initial boost. 📈

**Comment by nelsonic** [comment]
@LuchoTurtle how close do _you_ feel this repo is to sharing on `HN`? 💭 🚀

**Comment by LuchoTurtle** [comment]
Safe some changes to the README (as outlined on this issue), I think it brings sufficient value for those that want to get started with `Bumblebee` (unfortunately there aren't many examples out there with in-depth guides and comparisons).

However, I think #18 would also bring great value to this project and would be extremely interesting as it would use a part of `Bumblebee` that is not used here - `voice-to-text`.

**Comment by ndrean** [comment]
I can push several versions if you want help. 1) add an audio capture (an HTML <audio> addition with its JS Hook to upload to the server where we add a :speech allow_upload 2) ts handle_progress where you introduce the Speech-to-Text ML transcription 3) add embeddings and the KNN search. Let me know

**Comment by ndrean** [comment]
@LuchoTurtle I understand your idea. Note that the key point of selecting the right model is probably the most difficult part. However, I  did no effort on this. I just followed and adapted an article of Sean Moriarty on semantic search with ExFauss and adapted it. . It just works, and I feel I did not really learnt something - except the Elixir point of view if using tasks - in the sense that if you ask for something more difficult, like say an interactive LLM or build a model, then I have clearly no clue what to do. It's more like a one shot. But you have to start somewhere don't you!?  Anyway, I always cite my sources and will push things as soon as my computer is available.
