### ISSUE TITLE
Feat: Record `Video` Tutorial for this Repo! 📺 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-classifier#23]
@LuchoTurtle as discussed verbally, we're going to showcase this repo using `Video`.

Once we've tidied up the repo and landing page a bit #7 + #22 ✨ 
and added the DB (can be `SQLite`) to save metadata + classification #3  🔋 
We should plan to create a **_`Video`_ Tutorial** of this project. 🎥 

> **Note**: The objective is two-fold: 
> 1. Make a world class tutorial that _anyone_ can follow. 
> 2. Showcase _your_ @LuchoTurtle communication & technical skills 

# Todo

+ [ ] Ensure that the instructions in the `README.md` are fully up-to-date  👀 
  + [ ] and any external links are correct 🔗 
+ [ ] Setup your desktop/environment to _minimise_ distraction e.g. don't use your `Chrome` 
+ [ ] Follow the example by `Code to the Moon`: https://www.youtube.com/@codetothemoon/videos e.g: https://youtu.be/jib1wjgIaa4 we have all the equipment necessary to have a similar aesthetic. 😍 
+ [ ] Record your screen at `1080p` (e.g: connect to an external `1080p` monitor and record that) 📺 
  + [ ] Record your _voice_ explaining what you are doing while you are doing it. 🎤 
  + [ ] ***Optionally*** record your Face while you are going through the tutorial 👨‍🏫 
+ [ ] Re-Create the Project from scratch following the instructions in the `README.md` 🆕 
+ [ ] Add the code as per the `README.md` instructions 🧑‍💻 
+ [ ] Get the project to the "Wow" moment of classifying an uploaded image 🤩 
+ [ ] Speed run Fly.io deployment (don't focus on this part ...)

+ [ ] Transfer the captured screen recording to the `Mac Mini` for `DaVinci Resolve` Editing 🎬 
  (happy to pair with you on this ...) using the speed editor/keyboard. 
+ [ ] ***`Edit`*** the `Video` Tutorial to be as tight as possible (speed up any downloads) and 
  + [ ] Add _subtle/tasteful_ transitions 💄 between screens.
+ [ ] Publish the Tutorial to the `@dwyl` YT channel. 🚀

**Comment by nelsonic** [comment]
@LuchoTurtle when you feel the repo is “ready” for wider publication, please let’s get on a call and go through what is needed for recording the video with the highest possible production quality (image & sound). 
forget about _applying_ for jobs and doing pointless interview prep when there a _thousand_ other candidates. Unless you _personally_ know the hiring manager, the only way for them to **GET** to “know” you, your abilities/skills and _communication_ is by recording a Video. It’s the reason people are required to submit a video as part of their application to YCombinator https://www.ycombinator.com/video.html or Founders & Coders.
once the video is published you share it on your LinkedIn and set your profile to “available for hire” and let the recruiters come to you!

**Comment by LuchoTurtle** [comment]
Before tackling this issue, I need to get #18 sorted first and then change the frontend afterwards (haven't created an issue for this, will depend on how #18 is implemented). Only then I'll start recording a tutorial. 

But #18 is quite a tall task to have it fully documented and tested. Though I feel it is close to being completed, there's testing that still needs to be done. Having semantic search will make this repo super duper useful imo :)

**Comment by nelsonic** [comment]
Audio-to-text (#18) was never the purpose of this repo. 
It's an ***image*** classifier _not_ a speech-to-text demo. 
This is the _definition_ of ["feature creep"](https://en.wikipedia.org/wiki/Feature_creep).
Not saying that this isn't a nice-to-have feature, just _definitely_ not something that we need. 
I would _much_ prefer to split the audio-to-text out into a _separate_ repo to avoid complicating this one. 
I should have made that clearer back in November... ⏳ 💭 
I thought it was just going to be a "quick" addition. But it's really not ... 😕 

Please _completely ignore_ audio-to-text _completely_ for the purposes of the Video Tutorial. 
The audio-to-text should not be on the home page of this app. 
It can be on a dedicated page as a _separate_ demo. But it's not the focus. 

Semantic search is useful, yes. But only if the person uploading an image doesn't get the desired classification. 
The whole point of this project was to allow _us_ to upload an image and have it classified. That's it. 
Anything else is certainly a "bonus" but not the _focus_. 

Avoiding recording the video because a nice-to-have non-core feature isn't done yet 
is like people who procrastinate on fitness because they don't have the "right" water bottle. 🤦‍♂️ 

Just get the the video done for the "baseline" features so that the video is a _brief_ as possible. 
At the end of the video you can take 10 seconds to describe the "advanced" features (Semantic Search + Audio-to-Text)
and _ask_ people if they want a follow-up video walking through them.

**Comment by ndrean** [comment]
@nelsonic @LuchoTurtle  Just realised your comment above.
I did not know you didn't want semantic search __at all__. 

In fact, I realise I didn't know your scope. Just thought it was a nice addition. I shouldn't have spent time nor having made Lucho waste his time on this. First & last lesson, for sure.

**Comment by nelsonic** [comment]
@ndrean not at all. Semantic Search is a great feature. It's just beyond our _initial_ scope. 😉
