### ISSUE TITLE
Feat: Deploy to Fly.io 🚀 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-classifier#4]
@LuchoTurtle following on from the great work you've been doing on https://github.com/dwyl/image-classifier/pull/2 😍 
It's time to _deploy_ this project (and model) to Fly.io 

~~You've been invited to~~ You're **`admin`** on the following `new` org: https://fly.io/dashboard/dwyl-img-class

# Todo

+ [x] Create a new branch and Pull Request off the `initial` branch so you don't have to _wait_ for me to review it. 🆕 
+ [x] deploy the app as **`imgai`** or some other short+catchy name that is available on `fly.dev` 🌹 
+ [x] ensure that the app has auto-shut-down to conserve resources. Ref: https://fly.io/docs/apps/autostart-stop 📈 📉 👌 
  That way we can have a `2GB RAM` machine (or whatever you end up needing) and not run it 24/7 wasting cash. 💸 🔥 
   + [x] If you need to scale it up and have it always-on so that it's extra fast for a week or two when you're doing ["interviews"](https://github.com/dwyl/private/issues/6) we can easily do that. 😉 
+ [x] If prompted to create a `Database`, go with "Yes" as you will be needing it for the _next_ task: https://github.com/dwyl/image-classifier/issues/3

Thankfully this _should_ be reasonably straightforward as you've already done _most_ of the work to get it all running on `localhost` and have deployed _several_ apps to Fly.io over the last year.
